version: "3"
 ########################################################
 # Exported ports
 #   - 27017 => mongoDB
 #   - 8081  => mongo-express
 #   - 8080  => challenge app
services:

  # https://hub.docker.com/_/mongo/
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mexpress:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  challenge:
    image: maven
    ports:
      - 8080:8080
    links: 
      - mongo
    volumes:
      - ./:/mnt
      - ./:/root/.m2
    working_dir: /mnt
    command: bash -c "sleep 2 && mvn clean && mvn -DskipTests -Dspring.data.mongodb.username=root -Dspring.data.mongodb.password=example spring-boot:run"
